id: SUB-CREATE-SCHEMA-VALIDATOR
layer: SubTask
title: Create tw_validate.py schema validation tool
description: >
  Implement tw_validate.py that loads todowrite.schema.json, scans all
  YAML files in configs/plans/* directories, validates each against schema,
  and reports errors with file locations and specific validation failures.
  Include command-line interface with --strict and --summary options.
metadata:
  owner: validation-engineer
  labels: [work:validation, schema, yaml, error-reporting]
  severity: high
  work_type: validation
links:
  parents: [TSK-IMPLEMENT-VALIDATION-TOOLS]
  children: []