id: SUB-RUN-COMPATIBILITY-TESTS
layer: SubTask
title: Run comprehensive backward compatibility tests
description: >
  Execute automated tests validating all 29 existing YAML nodes against
  the extended schema. Create test suite to prevent future regression and
  verify that new schema accepts both old format (without status) and new
  format (with status fields) correctly.
metadata:
  owner: schema-engineer
  labels: ["work:validation", automated-testing, regression-prevention, test-suite]
  severity: high
  work_type: validation
links:
  parents: [TSK-TEST-SCHEMA-COMPATIBILITY]
  children: []
