id: SUB-ADD-STATUS-TO-TRACE
layer: SubTask
title: Add status information to traceability reports
description: >
  Enhance tw_trace.py to include status and progress information in trace.csv
  and graph.json outputs. Add status-based filtering and progress aggregation
  through dependency chains. Include visual indicators for blocked nodes.
metadata:
  owner: validation-engineer
  labels: ["work:validation", trace-enhancement, status-filtering, progress-aggregation]
  severity: med
  work_type: validation
links:
  parents: [TSK-UPDATE-TRACE-TOOL]
  children: []
