id: SUB-DOCUMENT-STATUS-FIELDS
layer: SubTask
title: Document status tracking schema fields
description: >
  Create comprehensive documentation for all status fields including field
  descriptions, validation rules, usage examples, and best practices.
  Include migration guide from current system to status-enabled version.
metadata:
  owner: documentation-engineer
  labels: ["work:docs", field-documentation, validation-rules, migration-guide]
  severity: med
  work_type: docs
links:
  parents: [TSK-WRITE-STATUS-SCHEMA-DOCS]
  children: []
