id: SUB-IMPLEMENT-MARK-COMPLETE
layer: SubTask
title: Implement mark-complete CLI command
description: >
  Create CLI command "todowrite status complete {node-id}" that automatically
  sets status to completed, progress to 100, and completion_date to current
  timestamp. Include option to mark entire subtree as complete with confirmation.
metadata:
  owner: cli-developer
  labels: ["work:implementation", cli-command, auto-timestamps, confirmation]
  severity: high
  work_type: implementation
links:
  parents: [TSK-ADD-STATUS-COMMANDS]
  children: []
