id: SUB-CREATE-MAKEFILE-BASIC-STRUCTURE
layer: SubTask
title: Create basic Makefile structure with core targets
description: >
  Create Makefile with basic structure including tw-deps (pip install requirements),
  tw-init (mkdir -p configs/plans/* configs/commands trace results),
  tw-clean (rm -rf trace/* results/*), and help target with target descriptions.
metadata:
  owner: build-engineer
  labels: ["work:implementation", makefile, basic-targets, structure]
  severity: high
  work_type: implementation
links:
  parents: [TSK-CREATE-MAKEFILE-STRUCTURE]
  children: []
