id: SUB-IMPLEMENT-UPDATE-STATUS
layer: SubTask
title: Implement update-status CLI command
description: >
  Create CLI command "todowrite status update {node-id} --status {value} --progress {0-100}"
  with proper input validation, YAML file modification, and error handling.
  Command should validate node exists, status enum values, and progress range.
metadata:
  owner: cli-developer
  labels: ["work:implementation", cli-command, input-validation, yaml-modification]
  severity: high
  work_type: implementation
links:
  parents: [TSK-ADD-STATUS-COMMANDS]
  children: []
