id: IF-STATUS-TRACKING-API
layer: InterfaceContract
title: Status Tracking API and CLI Interface Specification
description: >
  CLI Commands: todowrite status update {node-id} --status {value} --progress {0-100}
  todowrite status show --format {tree|flat|json} --filter {status}
  todowrite status report --since {date} --include-completed
  Schema Fields: status (planned|in_progress|completed|blocked|cancelled),
  progress (0-100), started_date (ISO 8601), completion_date (ISO 8601),
  assignee (string). All fields optional for backward compatibility.
  Status propagation: parent status derived from children completion.
metadata:
  owner: interface-designer
  labels: ["work:interface", api, cli, schema, status-fields]
  severity: high
  work_type: interface
links:
  parents: [AC-SCHEMA-BACKWARD-COMPATIBLE, AC-STATUS-COMMANDS-FUNCTIONAL, AC-VALIDATION-TOOLS-UPDATED, AC-STATUS-DOCUMENTATION-COMPLETE]
  children: [PH-STATUS-TRACKING-IMPLEMENTATION]
