id: IF-TODOWRITE-API-SCHEMA
layer: InterfaceContract
title: ToDoWrite API and CLI Interface Specification
description: >
  CLI Commands: todowrite create {layer} {id} --title "..." --description "..."
  API Endpoints: POST /api/v1/{layer}/, GET /api/v1/{layer}/{id},
  PUT /api/v1/{layer}/{id}, DELETE /api/v1/{layer}/{id}
  Schema Validation: All YAML must validate against todowrite.schema.json
  File Naming: {LAYER_PREFIX}-{IDENTIFIER}.yaml in configs/plans/{layer}/
  ID Pattern: ^(GOAL|CON|CTX|CST|R|AC|IF|PH|STP|TSK|SUB|CMD)-[A-Z0-9_-]+$
  Command Results: JSON artifacts in results/{CMD-ID}/ directory
metadata:
  owner: interface-designer
  labels: ["work:interface", api, cli, schema, naming]
  severity: high
  work_type: interface
links:
  parents: [AC-MAKEFILE-TARGETS-COMPLETE, AC-VALIDATION-TOOLS-FUNCTIONAL, AC-CLI-COMMANDS-INTEGRATED, AC-DOCUMENTATION-COMPLETE]
  children: []
