"""Initial migration for SQLAlchemy 2 models

Revision ID: 9c692b45aedb
Revises: 
Create Date: 2025-11-11 17:55:55.217500

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c692b45aedb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("labels",
    sa.Column("label", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("label")
    )
    op.create_table("nodes",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("layer", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("progress", sa.Integer(), nullable=True),
    sa.Column("started_date", sa.String(), nullable=True),
    sa.Column("completion_date", sa.String(), nullable=True),
    sa.Column("owner", sa.String(), nullable=True),
    sa.Column("severity", sa.String(), nullable=True),
    sa.Column("work_type", sa.String(), nullable=True),
    sa.Column("assignee", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("commands",
    sa.Column("node_id", sa.String(), nullable=False),
    sa.Column("ac_ref", sa.String(), nullable=True),
    sa.Column("run", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(["node_id"], ["nodes.id"] ),
    sa.PrimaryKeyConstraint("node_id")
    )
    op.create_table("links",
    sa.Column("parent_id", sa.String(), nullable=False),
    sa.Column("child_id", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["child_id"], ["nodes.id"] ),
    sa.ForeignKeyConstraint(["parent_id"], ["nodes.id"] ),
    sa.PrimaryKeyConstraint("parent_id", "child_id")
    )
    op.create_table("node_labels",
    sa.Column("node_id", sa.String(), nullable=False),
    sa.Column("label", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["label"], ["labels.label"] ),
    sa.ForeignKeyConstraint(["node_id"], ["nodes.id"] ),
    sa.PrimaryKeyConstraint("node_id", "label")
    )
    op.create_table("artifacts",
    sa.Column("artifact", sa.String(), nullable=False),
    sa.Column("command_id", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["command_id"], ["commands.node_id"] ),
    sa.PrimaryKeyConstraint("artifact", "command_id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifacts")
    op.drop_table("node_labels")
    op.drop_table("links")
    op.drop_table("commands")
    op.drop_table("nodes")
    op.drop_table("labels")
    # ### end Alembic commands ###
