from typing import Any

class Digraph:
    def __init__(self, name: str | None = ..., format: str | None = ..., **kwargs: Any) -> None: ...
    def node(self, name: str, label: str | None = ..., **kwargs: Any) -> None: ...
    def edge(
        self, tail_name: str, head_name: str, label: str | None = ..., *args: Any, **kwargs: Any
    ) -> None: ...
    def attr(self, *args: Any, **kwargs: Any) -> None: ...
    def body(self) -> str: ...
    def source(self) -> str: ...
    def render(
        self,
        filename: str | None = ...,
        view: bool = ...,
        format: str | None = ...,
        cleanup: bool = ...,
        **kwargs: Any,
    ) -> str: ...

def Digraph_factory(*args: Any, **kwargs: Any) -> Digraph: ...
