from typing import Optional, Any

class Digraph:
    def __init__(
        self, name: Optional[str] = ..., format: Optional[str] = ..., **kwargs: Any
    ) -> None: ...
    def node(self, name: str, label: Optional[str] = ..., **kwargs: Any) -> None: ...
    def edge(
        self, tail_name: str, head_name: str, label: Optional[str] = ..., *args: Any, **kwargs: Any
    ) -> None: ...
    def attr(self, *args: Any, **kwargs: Any) -> None: ...
    def body(self) -> str: ...
    def source(self) -> str: ...
    def render(
        self,
        filename: Optional[str] = ...,
        view: bool = ...,
        format: Optional[str] = ...,
        cleanup: bool = ...,
        **kwargs: Any,
    ) -> str: ...

def Digraph_factory(*args: Any, **kwargs: Any) -> Digraph: ...
