id: TSK-TEST-SCHEMA-COMPATIBILITY
layer: Task
title: Test schema backward compatibility with existing nodes
description: >
  Validate all existing 29 YAML nodes against the extended schema to ensure
  complete backward compatibility. Create automated tests to prevent regression
  and verify that new optional fields work correctly when present.
metadata:
  owner: schema-engineer
  labels: ["work:validation", compatibility-testing, regression-testing, automation]
  severity: high
  work_type: validation
links:
  parents: [STP-EXTEND-SCHEMA]
  children: [SUB-RUN-COMPATIBILITY-TESTS]
