id: TSK-ADD-STATUS-COMMANDS
layer: Task
title: Add status management CLI commands
description: >
  Implement CLI commands including update-status for setting node status and
  progress, mark-complete for marking nodes as completed with timestamps,
  and status-report for generating project progress summaries. Integrate with
  existing todowrite CLI structure.
metadata:
  owner: cli-developer
  labels: ["work:implementation", cli-commands, status-management, timestamps]
  severity: high
  work_type: implementation
links:
  parents: [STP-IMPLEMENT-STATUS-CLI]
  children: [SUB-IMPLEMENT-UPDATE-STATUS, SUB-IMPLEMENT-MARK-COMPLETE]
