id: CMD-VALIDATION-TOOLS-FUNCTIONAL
layer: Command
title: Execute validation for All validation tools execute successfully with proper
  error handling
description: 'Automated execution to verify: PASS: tw_validate.py validates YAML against
  schema with clear error messages, tw_lint_soc.py detects SoC violations in layers
  1-11, tw_trace.py generates complete trace.csv and graph.json, tw_stub_com...'
metadata:
  owner: validation-engineer
  labels:
  - generated
  - automated
  - verification
  severity: high
  work_type: validation
links:
  parents:
  - AC-VALIDATION-TOOLS-FUNCTIONAL
  children: []
command:
  ac_ref: AC-VALIDATION-TOOLS-FUNCTIONAL
  run:
    shell: python todowrite/tools/tw_validate.py --strict
    workdir: .
    env:
      TODOWRITE_MODE: validation
      AC_REF: AC-VALIDATION-TOOLS-FUNCTIONAL
  artifacts:
  - results/CMD-VALIDATION-TOOLS-FUNCTIONAL/execution.log
  - results/CMD-VALIDATION-TOOLS-FUNCTIONAL/validation_report.json
  - results/CMD-VALIDATION-TOOLS-FUNCTIONAL/schema_errors.log
