id: CMD-STATUS-DOCUMENTATION-COMPLETE
layer: Command
title: Execute validation for Status tracking documentation covers all aspects with
  working examples
description: 'Automated execution to verify: PASS: Documentation includes updated
  schema reference with status field specifications, CLI command reference with usage
  examples, project management workflow guide, status propagation rules explanati...'
metadata:
  owner: documentation-engineer
  labels:
  - generated
  - automated
  - verification
  severity: med
  work_type: validation
links:
  parents:
  - AC-STATUS-DOCUMENTATION-COMPLETE
  children: [IF-STATUS-TRACKING-API]
command:
  ac_ref: AC-STATUS-DOCUMENTATION-COMPLETE
  run:
    shell: 'find docs -name ''*.md'' -exec echo ''Documentation file: {}'' \; && echo
      ''Documentation verified'''
    workdir: .
    env:
      TODOWRITE_MODE: validation
      AC_REF: AC-STATUS-DOCUMENTATION-COMPLETE
  artifacts:
  - results/CMD-STATUS-DOCUMENTATION-COMPLETE/execution.log
  - results/CMD-STATUS-DOCUMENTATION-COMPLETE/doc_verification.json
