id: CMD-MAKEFILE-TARGETS-COMPLETE
layer: Command
title: Execute validation for All tw-* Makefile targets implemented and functional
description: 'Automated execution to verify: PASS: All 12 required Makefile targets
  (tw-deps, tw-init, tw-all, tw-schema, tw-lint, tw-validate, tw-trace, tw-prove,
  tw-hooks, tw-clean, tw-check, tw-test) execute successfully without errors and pr...'
metadata:
  owner: build-engineer
  labels:
  - generated
  - automated
  - verification
  severity: high
  work_type: validation
links:
  parents:
  - AC-MAKEFILE-TARGETS-COMPLETE
  children: [IF-TODOWRITE-API-SCHEMA]
command:
  ac_ref: AC-MAKEFILE-TARGETS-COMPLETE
  run:
    shell: make tw-all && echo 'Makefile targets verified'
    workdir: .
    env:
      TODOWRITE_MODE: validation
      AC_REF: AC-MAKEFILE-TARGETS-COMPLETE
  artifacts:
  - results/CMD-MAKEFILE-TARGETS-COMPLETE/execution.log
  - results/CMD-MAKEFILE-TARGETS-COMPLETE/make_output.log
  - configs/schemas/todowrite.schema.json
