id: R-MAKEFILE-AUTOMATION
layer: Requirements
title: Complete Makefile with tw-* targets
description: >
  The system SHALL provide a Makefile with all required tw-* targets
  including tw-deps, tw-init, tw-all, tw-schema, tw-lint, tw-validate,
  tw-trace, tw-prove, tw-hooks, tw-clean, tw-check, tw-test for
  complete workflow automation.
metadata:
  owner: build-engineer
  labels: ["work:implementation", makefile, automation, build]
  severity: high
  work_type: implementation
links:
  parents: [CST-SYSTEM-CONSTRAINTS]
  children: [AC-MAKEFILE-TARGETS-COMPLETE]
