id: R-SCHEMA-EXTENSION
layer: Requirements
title: JSON Schema Extension for Status Tracking
description: >
  The system SHALL extend the existing JSON schema to include optional status
  tracking fields: status (enum: planned, in_progress, completed, blocked, cancelled),
  progress (integer 0-100), started_date (ISO 8601 string), completion_date
  (ISO 8601 string), and assignee (string). All fields must be optional to
  maintain backward compatibility with existing nodes.
metadata:
  owner: schema-engineer
  labels: ["work:validation", schema, json, optional-fields, status]
  severity: high
  work_type: validation
links:
  parents: [CST-ENHANCEMENT-CONSTRAINTS]
  children: [AC-SCHEMA-BACKWARD-COMPATIBLE]
