id: R-VALIDATION-TOOLS
layer: Requirements
title: Build-time validation tool suite
description: >
  The system SHALL provide validation tools including tw_validate.py
  for JSON Schema validation, tw_lint_soc.py for Separation of Concerns
  linting, tw_trace.py for traceability matrix building, and
  tw_stub_command.py for command stub generation from Acceptance Criteria.
metadata:
  owner: validation-engineer
  labels: ["work:validation", tools, schema, linting, traceability]
  severity: high
  work_type: validation
links:
  parents: [CST-SYSTEM-CONSTRAINTS]
  children: [AC-VALIDATION-TOOLS-FUNCTIONAL]
